#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          wiot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: wiot
# Description:       wiot
### END INIT INFO

# Author: Michal Grezl

DESC="wiot"
DAEMON=/usr/local/bin/wiot

case "$1" in
  start)
	/usr/local/bin/wiot.pl &
	;;
  restart|reload|force-reload)
	
	$0 stop
        sleep 1
	$0 start
	;;
  stop)
	killall wiot.pl
	;;
  status)
	exit $?
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac

:
